# Generated by Django 2.1.5 on 2019-04-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='student',
            table='e_student',
        ),
    ]
