# Generated by Django 2.1.5 on 2019-04-23 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('User', '0002_auto_20190423_1215'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'e_course',
            },
        ),
        migrations.CreateModel(
            name='E_State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.IntegerField()),
            ],
            options={
                'db_table': 'e_state',
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'evaluation',
            },
        ),
        migrations.CreateModel(
            name='S_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'e_s_couser',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'subject',
            },
        ),
        migrations.CreateModel(
            name='T_Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Course')),
            ],
            options={
                'db_table': 'e_t_couser',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'e_teacher',
            },
        ),
        migrations.RenameField(
            model_name='student',
            old_name='school',
            new_name='team',
        ),
        migrations.AddField(
            model_name='t_course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Teacher'),
        ),
        migrations.AddField(
            model_name='s_course',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Student'),
        ),
        migrations.AddField(
            model_name='s_course',
            name='t_course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.T_Course'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Student'),
        ),
        migrations.AddField(
            model_name='evaluation',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Teacher'),
        ),
        migrations.AddField(
            model_name='e_state',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Student'),
        ),
        migrations.AddField(
            model_name='e_state',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Teacher'),
        ),
    ]
