# Generated by Django 2.1.5 on 2019-05-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20190423_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='birthday',
            field=models.DateField(default='1996-02-02'),
        ),
        migrations.AddField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='nopic.jpg', upload_to='files'),
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default='王同学', max_length=12),
        ),
        migrations.AddField(
            model_name='student',
            name='sex',
            field=models.CharField(default='男', max_length=3),
        ),
        migrations.AddField(
            model_name='student',
            name='telephone',
            field=models.CharField(default='18772815717', max_length=11),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.CharField(default='软件151', max_length=100),
        ),
    ]
