# Generated by Django 2.1.5 on 2019-05-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20190508_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(default='1969-02-02'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.ImageField(blank=True, default='nopic.jpg', upload_to='files'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='name',
            field=models.CharField(default='王老师', max_length=12),
        ),
        migrations.AddField(
            model_name='teacher',
            name='sex',
            field=models.CharField(default='男', max_length=3),
        ),
        migrations.AddField(
            model_name='teacher',
            name='telephone',
            field=models.CharField(default='18772815717', max_length=11),
        ),
    ]
