# Generated by Django 2.1.5 on 2019-05-08 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20190508_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='birthday',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
