# Generated by Django 2.1.5 on 2019-05-08 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_auto_20190508_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(default='王同学', max_length=4),
        ),
        migrations.AlterField(
            model_name='student',
            name='sex',
            field=models.CharField(default='男', max_length=1),
        ),
        migrations.AlterField(
            model_name='student',
            name='team',
            field=models.CharField(default='软件151', max_length=8),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='birthday',
            field=models.DateField(default='1996-02-02'),
        ),
    ]
