# Generated by Django 2.1.5 on 2019-05-09 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20190508_1731'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='number',
            field=models.SmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='subject',
            name='score',
            field=models.IntegerField(default=18),
        ),
    ]
