# Generated by Django 2.1.5 on 2019-05-09 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0010_auto_20190509_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='number',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
