# Generated by Django 2.1.5 on 2019-05-09 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_auto_20190509_1416'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='score',
        ),
        migrations.AddField(
            model_name='evaluation',
            name='score',
            field=models.IntegerField(default=18),
        ),
    ]
