# Generated by Django 2.1.5 on 2019-05-09 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0012_auto_20190509_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='img',
            field=models.ImageField(blank=True, default='nopic.jpg', help_text='大小200*200，不超过200k', upload_to='files', verbose_name='缩略图'),
        ),
    ]
