# Generated by Django 2.1.5 on 2019-05-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0015_administrators'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='number',
        ),
    ]
